version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - npm install -g pnpm
      - pnpm install
  build:
    commands:
      - echo "API_URL=$NEXT_PUBLIC_API_URL"
      - pnpm run build
artifacts:
  base-directory: out
  files:
    - '**/*'